"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$username\
$hostname\
[](bg:blue fg:surface0)\
$directory\
[](bg:teal fg:blue)\
$git_branch\
$git_status\
[](fg:teal bg:mauve)\
$php\
$python\
$golang\
$c\
$rust\
$java\
$kotlin\
$haskell\
[](fg:mauve bg:overlay1)\
$conda\
[](fg:overlay1 bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'bigwoo_nordic_monolith'

[username]
show_always = false
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[hostname]
disabled = false
ssh_only = false
trim_at = "."
style = "bg:surface0 fg:text"
format = '[ $hostname ]($style)'

[directory]
style = "bg:blue fg:crust"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:crust bg:teal)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:crust bg:teal)]($style)'

[c]
symbol = " "
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[rust]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[golang]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[php]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[java]
symbol = " "
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[kotlin]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[haskell]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[python]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:text bg:mauve)]($style)'

[docker_context]
symbol = ""
style = "bg:overlay1"
format = '[[ $symbol( $context) ](fg:text bg:overlay1)]($style)'

[conda]
symbol = "  "
style = "fg:text bg:overlay1"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:teal)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:teal)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.bigwoo_nordic_monolith]
rosewater = "#ECEFF4"
flamingo = "#E5E9F0"
pink = "#D8DEE9"
mauve = "#4C566A"
red = "#BF616A"
maroon = "#A3BE8C"
peach = "#88C0D0"
yellow = "#EBCB8B"
green = "#8FBCBB"
teal = "#8FBCBB"
sky = "#88C0D0"
sapphire = "#81A1C1"
blue = "#81A1C1"
lavender = "#D8DEE9"
text = "#ECEFF4"
subtext1 = "#E5E9F0"
subtext0 = "#D8DEE9"
overlay2 = "#616E88"
overlay1 = "#4C566A"
overlay0 = "#434C5E"
surface2 = "#3B4252"
surface1 = "#2E3440"
surface0 = "#2E3440"
base = "#242933"
mantle = "#1F2430"
crust = "#11151C"
