"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$username\
$hostname\
[](bg:blue fg:surface0)\
$directory\
[](bg:teal fg:blue)\
$git_branch\
$git_status\
[](fg:teal bg:mauve)\
$php\
$python\
$golang\
$c\
$rust\
$java\
$kotlin\
$haskell\
[](fg:mauve bg:overlay1)\
$conda\
[](fg:overlay1 bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'bigwoo_tokyo_dusk'

[username]
show_always = false
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[hostname]
disabled = false
ssh_only = false
trim_at = "."
style = "bg:surface0 fg:text"
format = '[ $hostname ]($style)'

[directory]
style = "bg:blue fg:crust"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:crust bg:teal)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:crust bg:teal)]($style)'

[c]
symbol = " "
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:crust bg:mauve)]($style)'

[rust]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:crust bg:mauve)]($style)'

[golang]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:crust bg:mauve)]($style)'

[php]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:crust bg:mauve)]($style)'

[java]
symbol = " "
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:crust bg:mauve)]($style)'

[kotlin]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:crust bg:mauve)]($style)'

[haskell]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:crust bg:mauve)]($style)'

[python]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:mauve)]($style)'

[docker_context]
symbol = ""
style = "bg:overlay1"
format = '[[ $symbol( $context) ](fg:text bg:overlay1)]($style)'

[conda]
symbol = "  "
style = "fg:text bg:overlay1"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.bigwoo_tokyo_dusk]
rosewater = "#F5E0DC"
flamingo = "#EBA0AC"
pink = "#F5C2E7"
mauve = "#9D7CD8"
red = "#F7768E"
maroon = "#B85C7A"
peach = "#FF9E64"
yellow = "#E0AF68"
green = "#73DACA"
teal = "#73DACA"
sky = "#7DCFFF"
sapphire = "#7AA2F7"
blue = "#7AA2F7"
lavender = "#B4BEFE"
text = "#C0CAF5"
subtext1 = "#A9B1D6"
subtext0 = "#9AA5CE"
overlay2 = "#787C99"
overlay1 = "#565F89"
overlay0 = "#414868"
surface2 = "#414868"
surface1 = "#2F3549"
surface0 = "#1F2335"
base = "#1A1B26"
mantle = "#16161E"
crust = "#11111B"
