"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$username\
$hostname\
[](fg:surface0 bg:peach)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:mauve)\
$php\
$python\
$golang\
$c\
$rust\
$java\
$kotlin\
$haskell\
[](fg:mauve bg:overlay1)\
$conda\
[](fg:overlay1 bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'bigwoo_vintage_terminal'

[username]
show_always = false
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[hostname]
disabled = false
ssh_only = false
trim_at = "."
style = "bg:surface0 fg:text"
format = '[ $hostname ]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:crust bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[rust]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[golang]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[php]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[java]
symbol = " "
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[kotlin]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[haskell]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version) ](fg:text bg:mauve)]($style)'

[python]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:text bg:mauve)]($style)'

[docker_context]
symbol = ""
style = "bg:overlay1"
format = '[[ $symbol( $context) ](fg:text bg:overlay1)]($style)'

[conda]
symbol = "  "
style = "fg:text bg:overlay1"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.bigwoo_vintage_terminal]
rosewater = "#F5E6C8"
flamingo = "#E6C7A1"
pink = "#D7A86E"
mauve = "#8B4513"
red = "#C26D2C"
maroon = "#9C5B1B"
peach = "#FFB000"
yellow = "#D9A441"
green = "#32CD32"
teal = "#4FAE4E"
sky = "#9BCB6C"
sapphire = "#6A8F4E"
blue = "#A0A0A0"
lavender = "#D1BFA3"
text = "#E8DEC9"
subtext1 = "#D3C8B2"
subtext0 = "#B8AF9C"
overlay2 = "#8A806F"
overlay1 = "#5E4C3E"
overlay0 = "#3B2C25"
surface2 = "#3A2A1C"
surface1 = "#241B16"
surface0 = "#101010"
base = "#0B0B0B"
mantle = "#080808"
crust = "#050505"
